-- root用户下
-- 创建用户
CREATE USER 'DREAMCUBE'@'localhost' IDENTIFIED BY 'DREAMCUBE';

-- 用户授权
GRANT USAGE ON *.* TO 'DREAMCUBE'@'localhost';

FLUSH PRIVILEGES;

--

CREATE DATABASE `DREAMCUBE` /*!40100 COLLATE 'utf8_general_ci' */;


-- 数据库授权

GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  
ON `DREAMCUBE`.* 
TO 'DREAMCUBE'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;

-- 时区
set global time_zone='+8:00';